### ISSUE TITLE
/bin/sh: 1: psftp: not found

### ISSUE THREAD

**Issue by BaseMax** [Luis97lol/psftp-action#1]
```
on: [push]

jobs:
  upload_to_sftp:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: P-SFTP
        uses: Luis97lol/PSFTP@v1.3
        with:
          host: 'xxxxxxxx.com'
          user: 'xxxxxxxx'
          pass: ${{ secrets.FTP_PASSWORD }}
          scriptPath: deploy.sh
```

Action Logs:

```
Run Luis97lol/PSFTP@v[1](https://github.com/BaseMax/KareMan/runs/8233919805?check_suite_focus=true#step:3:1).3
error: Command failed: psftp "xxxxxxxx.com" -l "xxxxxxxx" -pw "***" -b deploy.sh
/bin/sh: 1: psftp: not found
```

**Comment by Luis97lol** [comment]
Hi @BaseMax ! The action is correctly setted up on your .yml. The log error is due to the psftp executable not being installed correctly on the host machine. ¿Are you using GitHub Runners or Self-Hosted Runner?

**Comment by BaseMax** [comment]
Thank you for your message. It's GitHub Action

**Comment by Luis97lol** [comment]
I'm not tested it on GitHub Runner. @BaseMax You can try executing the installation command before running the action:
`apt-get install putty-tools`

**Comment by Luis97lol** [comment]
Hi @BaseMax ! I have reproduced the issue in one of my projects. The .yml pipeline file to run on a GitHub machine must contain the following line of code before running my GitHub Action
```
steps:
    - run: sudo apt-get install putty-tools
    - uses: Luis97lol/PSFTP@v1.3
      with:
        host: ${{ secrets.SFTP_HOST }}
        user: ${{ secrets.SFTP_USER }}
        pass: ${{ secrets.SFTP_PASS }}
        scriptPath: deploy.sh
```
